services:

  # ============================================================
  # Backend FastAPI - CI CPU
  # ============================================================

  backend:
    gpus: !reset []

    environment:
      EMBEDDING_DEVICE: cpu


  # ============================================================
  # Ollama - CI CPU
  # ============================================================

  ollama:
    gpus: !reset []